# Generated by Django 2.1.5 on 2019-01-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_count', models.IntegerField(default=0)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('release_by', models.CharField(max_length=255)),
                ('listeners', models.ManyToManyField(through='recommend.Listen', to='recommend.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='listen',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Song'),
        ),
    ]
