# Generated by Django 2.1.5 on 2019-01-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20190122_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listen',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='listeners',
        ),
        migrations.AddField(
            model_name='appuser',
            name='listens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommend.Listen'),
            preserve_default=False,
        ),
    ]
