# Generated by Django 2.1.5 on 2019-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20190122_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.CharField(default=2010, max_length=4),
            preserve_default=False,
        ),
    ]
