# Generated by Django 2.1.5 on 2019-01-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='', upload_to='albums'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
