# Generated by Django 2.1.5 on 2019-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20190122_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(default='', upload_to='albums'),
        ),
    ]
