# Generated by Django 2.1.5 on 2019-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20190122_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=1, upload_to='music'),
            preserve_default=False,
        ),
    ]
