# Generated by Django 2.1.5 on 2019-01-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_auto_20190123_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommend.AppUser'),
            preserve_default=False,
        ),
    ]
