# Generated by Django 2.1.5 on 2019-01-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_auto_20190123_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='listens',
        ),
    ]
