# Generated by Django 2.1.5 on 2019-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0017_auto_20190131_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_logo',
            field=models.ImageField(default='', upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='recommend.Song'),
        ),
    ]
